from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .video_nodes import NODE_CLASS_MAPPINGS as VIDEO_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NAMES
from .gpt_autogrow import NODE_CLASS_MAPPINGS as DYNAMIC_CLASSES
from .seedance_nodes import NODE_CLASS_MAPPINGS as SEEDANCE_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SEEDANCE_NAMES

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **VIDEO_CLASSES, **DYNAMIC_CLASSES, **SEEDANCE_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **VIDEO_NAMES, **SEEDANCE_NAMES}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
